Major cleanup for repository publication.

diff --git a/backup-mount b/backup-mount
--- a/backup-mount
+++ b/backup-mount
@@ -1,11 +1,15 @@
 #!/bin/bash
 
-# to mount a encrypted backup image over samba
-# by robert klebe
+# backup-mount
+# mount a encrypted backup image over samba
+# by robert klebe, dotpointer
 
 # changelog
 # 2014-11-05 14:37:27 - initial version
-# 2015-06-06 - making file a part of dptools
+# 2015-06-06 12:47:17 - making file a part of dptools
+# 2018-06-28 13:32:00 - cleanup
+# 2018-06-28 15:44:00 - description edit and cleanup
+
 
 # Make sure only root can run our script
 if [[ $EUID -ne 0 ]]; then
@@ -37,29 +41,52 @@ source $CONFIG_FILE;
 
 # check parameters
 
-if [ -z "$DIR_SHARE" ]; then echo "DIR_SHARE not set"; exit 1; fi
+if [ -z "$DIR_SHARE" ]; then
+	echo "DIR_SHARE not set";
+	exit 1;
+fi
 echo "Samba share mount point: $DIR_SHARE";
 
-if [ -z "$DIR_IMAGE" ]; then echo "DIR_IMAGE not set"; exit 1; fi
+if [ -z "$DIR_IMAGE" ]; then
+	echo "DIR_IMAGE not set";
+	exit 1;
+fi
 echo "Image file mount point : $DIR_IMAGE";
 
-if [ -z "$LOOPDEVICE" ]; then echo "LOOPDEVICE not set"; exit 1; fi
+if [ -z "$LOOPDEVICE" ]; then
+	echo "LOOPDEVICE not set";
+	exit 1;
+fi
 echo "Loop device: $LOOPDEVICE";
 
-if [ -z "$MAPPERNAME" ]; then echo "MAPPERNAME not set"; exit 1; fi
+if [ -z "$MAPPERNAME" ]; then
+	echo "MAPPERNAME not set";
+	exit 1;
+fi
 echo "Device mapper: /dev/mapper/$MAPPERNAME";
 
-if [ -z "$SAMBA_USER" ]; then echo "SAMBA_USER not set"; exit 1; fi
+if [ -z "$SAMBA_USER" ]; then
+	echo "SAMBA_USER not set";
+	exit 1;
+fi
 echo "Samba user: $SAMBA_USER";
 
-if [ -z "$SAMBA_PASSWORD" ]; then echo "SAMBA_PASSWORD not set"; exit 1; fi
+if [ -z "$SAMBA_PASSWORD" ]; then
+	echo "SAMBA_PASSWORD not set";
+	exit 1;
+fi
 
-if [ -z "$SAMBA_PATH_SHARE" ]; then echo "SAMBA_PATH_SHARE not set"; exit 1; fi
+if [ -z "$SAMBA_PATH_SHARE" ]; then
+	echo "SAMBA_PATH_SHARE not set";
+	exit 1;
+fi
 echo "Samba share path: $SAMBA_PATH_SHARE";
 
-if [ -z "$SAMBA_PATH_IMAGE" ]; then echo "SAMBA_PATH_IMAGE not set"; exit 1; fi
+if [ -z "$SAMBA_PATH_IMAGE" ]; then
+	echo "SAMBA_PATH_IMAGE not set";
+	exit 1;
+fi
 echo "Samba image path inside Samba share: $SAMBA_PATH_IMAGE";
-
 
 # make sure outer container dir is there
 echo "Checking share dir: $DIR_SHARE";
diff --git a/backup-sync b/backup-sync
--- a/backup-sync
+++ b/backup-sync
@@ -1,28 +1,32 @@
 #!/bin/bash
 
 # backup-sync
-# by robert klebe
+# copy data from source directories to target image file
+# by robert klebe, dotpointer
 
-# Make sure only root can run our script
+# changelog
+# 2015-06-06 12:47:39
+# 2018-06-28 13:32:00 - cleanup
+
+# make sure only root can run our script
 if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root"
-   exit 1
+	echo "This script must be run as root";
+	exit 1;
 fi
-      
-CONFIG_FILE="/etc/dptools/backuptools"
+
+CONFIG_FILE="/etc/dptools/backuptools";
 
 # defaults
-DIR_IMAGE="/mnt/backupimage"
+DIR_IMAGE="/mnt/backupimage";
 
 if [ ! -f "$CONFIG_FILE" ]; then
-   echo "Missing configuration file: $CONFIG_FILE";
-   exit 1;
+	echo "Missing configuration file: $CONFIG_FILE";
+	exit 1;
 fi
 
-source $CONFIG_FILE
+source $CONFIG_FILE;
 
-
-echo "Checking if $DIR_IMAGE is mounted"
+echo "Checking if $DIR_IMAGE is mounted";
 mountpoint $DIR_IMAGE
 if [[ $? != 0 ]]; then
 	echo "$DIR_IMAGE is not mounted, something is wrong.";
@@ -35,49 +39,46 @@ DIR_IMAGE="$DIR_IMAGE/";
 echo "Running rsyncs";
 
 if [ -n "$SYNC_CMD1" ]; then
-   echo "Running sync: $SYNC_CMD1";
-   $SYNC_CMD1
-   if [[ $? != 0 ]]; then
+	echo "Running sync: $SYNC_CMD1";
+	$SYNC_CMD1
+	if [[ $? != 0 ]]; then
 	echo "Sync failed will not continue";
 	exit 1;
-   fi      
+	fi
 fi
 
 if [ -n "$SYNC_CMD2" ]; then
-   echo "Running sync: $SYNC_CMD2";
-   $SYNC_CMD2
-   if [[ $? != 0 ]]; then
+	echo "Running sync: $SYNC_CMD2";
+	$SYNC_CMD2
+	if [[ $? != 0 ]]; then
 	echo "Sync failed will not continue";
 	exit 1;
-   fi      
+	fi
 fi
 
 if [ -n "$SYNC_CMD3" ]; then
-   echo "Running sync: $SYNC_CMD3";
-   $SYNC_CMD3
-   if [[ $? != 0 ]]; then
+	echo "Running sync: $SYNC_CMD3";
+	$SYNC_CMD3
+	if [[ $? != 0 ]]; then
 	echo "Sync failed will not continue";
 	exit 1;
-   fi   
+	fi
 fi
-
 
 if [ -n "$SYNC_CMD4" ]; then
-   echo "Running sync: $SYNC_CMD4";
-   $SYNC_CMD4
-   if [[ $? != 0 ]]; then
+	echo "Running sync: $SYNC_CMD4";
+	$SYNC_CMD4
+	if [[ $? != 0 ]]; then
 	echo "Sync failed will not continue";
 	exit 1;
-   fi      
+	fi
 fi
-
 
 if [ -n "$SYNC_CMD5" ]; then
-   echo "Running sync: $SYNC_CMD5";
-   $SYNC_CMD5
-   if [[ $? != 0 ]]; then
+	echo "Running sync: $SYNC_CMD5";
+	$SYNC_CMD5
+	if [[ $? != 0 ]]; then
 	echo "Sync failed will not continue";
 	exit 1;
-   fi      
+	fi
 fi
-
diff --git a/backup-umount b/backup-umount
--- a/backup-umount
+++ b/backup-umount
@@ -5,7 +5,8 @@
 
 # changelog
 # 2014-11-05 14:43:27 - initial version
-# 2015-06-06 - updated version for dptools
+# 2015-06-06 12:38:51 - updated version for dptools
+# 2018-06-28 15:53:00 - cleanup
 
 # credentials
 DIR_IMAGE="/mnt/backupimage";
@@ -13,19 +14,19 @@ DIR_SHARE="/mnt/backupshare";
 LOOPDEVICE="/dev/loop0";
 MAPPERNAME="backuploop";
 
-CONFIG_FILE="/etc/dptools/backuptools"
+CONFIG_FILE="/etc/dptools/backuptools";
 
 if [ ! -f "$CONFIG_FILE" ]; then
-    echo "Missing configuration file: $CONFIG_FILE";
-    exit 1;
+	echo "Missing configuration file: $CONFIG_FILE";
+	exit 1;
 fi
 
-source $CONFIG_FILE
+source $CONFIG_FILE;
 
 # Make sure only root can run our script
 if [[ $EUID -ne 0 ]]; then
-   echo "This script must be run as root"
-   exit 1
+   echo "This script must be run as root";
+   exit 1;
 fi
 
 # unmount the image dir
@@ -37,7 +38,7 @@ if [[ $? != 0 ]]; then
 fi
 
 # close the luks mapping
-echo "Closing LUKS mapper: /dev/mapper/$MAPPERNAME" 
+echo "Closing LUKS mapper: /dev/mapper/$MAPPERNAME";
 cryptsetup luksClose /dev/mapper/$MAPPERNAME
 if [[ $? != 0 ]]; then
 	echo "Failed closing LUKS mapper: /dev/mapper/$MAPPERNAME";
@@ -53,7 +54,7 @@ if [[ $? != 0 ]]; then
 fi
 
 # unmount the share dir
-echo "Unmounting share dir: $DIR_SHARE"
+echo "Unmounting share dir: $DIR_SHARE";
 umount $DIR_SHARE
 if [[ $? != 0 ]]; then
 	echo "Failed unmounting dir: $DIR_SHARE";
diff --git a/dptools-update b/dptools-update
--- a/dptools-update
+++ b/dptools-update
@@ -9,9 +9,7 @@
 # 2016-12-27 20:09:00 - adding removal of unnecessary files
 # 2017-02-01 19:08:00 - domain edit
 # 2017-07-28 12:53:00 - domain edit
-
-# where to put the cache file with the current timestamp
-cachefile="/var/cache/dptools.cache"
+# 2018-06-28 16:59:00 - switching source from dotpointer.ga to gitlab repository
 
 # target to put files into
 targetdir="/var/scripts/dptools"
@@ -19,118 +17,32 @@ targetdir="/var/scripts/dptools"
 # config dir
 configdir="/etc/dptools"
 
-basedomain="dotpointer.ga"
-
-# url to download files from
-downloadurl="http://www.$basedomain/service/?a=dptools"
-
-# url to check timestamp from
-timeurl="http://www.$basedomain/service/?a=dptools_time"
-
-# temporary file to store compressed file
-tmpfile="/tmp/dptools.tar.gz"
-
-# default localtime
-localtime=0
-
-# make sure we are root
-
 if [ ! $(whoami) == "root" ]; then
     echo "Root user is required to update the dptools"
     exit
 fi
 
-# is there a cachefile and it is readable?
-if test -r "$cachefile" -a -f "$cachefile"
+# does target dir exist
+if [ -d "$targetdir" ]; then
+	cd "$targetdir";
+	git pull
+	if [ ! $? -eq 0 ]; then
+		echo "Failed pulling data from git repository.";
+		exit 1;
+	fi
 then
-        echo "Reading current server version timestamp"
-        # get server time
-	servertime=$(wget "$timeurl" -q -O -)
-	
-	
-	if [ ! $? -eq 0 ] ; then
-	       echo "Failed retrieving current server version timestamp from $timeurl, no internet connection?";
-	       exit 1
-	fi
-
-        echo "Reading current local version timestamp"
-        # get local time from cachefile
-	localtime=$(cat $cachefile)
-	if [ ! $? -eq 0 ] ; then
-	      echo "Failed reading current local version timestamp from $cachefile, maybe it is not readable?";	      
-	      exit 1
-	fi
-
-        # output some info
-	# echo "Local version timestamp : $localtime"
-	# echo "Server version timestamp: $servertime"
-	
-	# is localtime >= servertime?
-	if [ "$localtime" -ge "$servertime" ]
-	then
-	     # then happily get out
-	     echo 'Update not required, local version is up to date';
-	     exit 0;
-	fi
 fi
 
-# update seems to be needed
-echo "Update required, downloading new version" # from $downloaddir"
-
-# download the new version to temp directory
-wget "$downloadurl" -q -O "$tmpfile"
-if [ ! $? -eq 0 ] ; then
-      echo "Failed downloading file from $downloadurl";
-      exit 1
-fi
-
-
-# make sure it exists
-if [ ! -f "$tmpfile" ]; then
-    echo "Downloaded temporary file $tmpfile not found"
-    exit
-fi
-
-# check target dir
+# does target dir not exist
 if [ ! -d "$targetdir" ]; then
-    echo "Creating directory $targetdir"
-    # make a directory
-    mkdir -p "$targetdir"
-    if [ ! $? -eq 0 ] ; then
-       echo "Failed creating directory $targetdir";
-       exit 1
-    fi
-fi
-
-# check configuration dir
-if [ ! -d "$configdir" ]; then
-    echo "Creating configuration directory $configdir"
-    # make a directory
-    mkdir -p "$configdir"
-    if [ ! $? -eq 0 ] ; then
-        echo "Failed creating directory $configdir";
-        exit 1
-    fi
-fi
-
-# extract contents
-echo "Extracting contents of $tmpfile to $targetdir"
-tar -xf $tmpfile -C $targetdir
-if [ ! $? -eq 0 ] ; then
-   echo "Failed creating directory $targetdir";
-      exit 1
-fi
-
-# remove the temp file
-echo "Removing temporary file $tmpfile"
-rm $tmpfile
-if [ ! $? -eq 0 ] ; then
-   echo "Failed removing temporary file $tmpfile";
-      exit 1
+	git clone https://gitlab.com/dotpointer/dptools.git /var/scripts/dptools
+	if [ ! $? -eq 0 ]; then
+		echo "Failed cloning data from git repository.";
+		exit 1;
+	fi
 fi
 
 # remove unnecessary files
-
 removefile="$targetdir/backup_databases"
 if [ -f "$removefile" ] ; then
 	echo "Removing unnecessary file: $removefile";
@@ -141,13 +53,48 @@ if [ -f "$removefile" ] ; then
 	fi
 fi
 
+# remove unnecessary files
+removefile="$targetdir/convdb-iso-8859-1-to-utf-8"
+if [ -f "$removefile" ] ; then
+	echo "Removing deprecated file: $removefile";
+	rm $removefile
+	if [ ! $? -eq 0 ] ; then
+		echo "Failed removing file $removefile";
+		exit 1
+	fi
+fi
 
-echo "Storing current timestamp"
-# store current time to file
-echo $servertime > $cachefile
-if [ ! $? -eq 0 ] ; then
-   echo "Failed storing current timestamp to $cachefile";
-      exit 1
+# remove deprecated files
+removefile="$targetdir/dpconvert"
+if [ -f "$removefile" ] ; then
+	echo "Removing deprecated file: $removefile";
+	rm $removefile
+	if [ ! $? -eq 0 ] ; then
+		echo "Failed removing file $removefile";
+		exit 1
+	fi
+fi
+
+# remove unnecessary files
+removefile="$targetdir/ka"
+if [ -f "$removefile" ] ; then
+	echo "Removing unnecessary file: $removefile";
+	rm $removefile
+	if [ ! $? -eq 0 ] ; then
+		echo "Failed removing file $removefile";
+		exit 1
+	fi
+fi
+
+# remove unnecessary files
+removefile="$targetdir/kc"
+if [ -f "$removefile" ] ; then
+	echo "Removing unnecessary file: $removefile";
+	rm $removefile
+	if [ ! $? -eq 0 ] ; then
+		echo "Failed removing file $removefile";
+		exit 1
+	fi
 fi
 
 echo "Setting 755 on dptools directory recursively"
@@ -161,7 +108,6 @@ then
   echo ""
   echo "$targetdir was not found in your PATH variable."
   echo ""
-  
   echo "This means that you cannot use the powers of dptools in this console."
   echo ""  
   echo "You need to add dp_console_setup.sh to your ~/.bashrc and ~/.profile files."
@@ -169,7 +115,7 @@ then
   echo "Open the files in an editor and add the following line at the end of them:"
   echo ". $targetdir/dp_console_setup.sh"
   echo ""
-  echo "Then reload: source ~/.profile"
+  echo "Then reload by running this: source ~/.profile"
 # or is it in the path
 else
   # then reload the profile
