Indentation change, tab to 2 spaces.

diff --git a/backup-mount b/backup-mount
--- a/backup-mount
+++ b/backup-mount
@@ -9,6 +9,7 @@
 # 2015-06-06 12:47:17 - making file a part of dptools
 # 2018-06-28 13:32:00 - cleanup
 # 2018-06-28 15:44:00 - description edit and cleanup
+# 2018-07-19 19:29:29 - indentation change, tab to 2 spaces
 
 
 # Make sure only root can run our script
@@ -42,78 +43,78 @@ source $CONFIG_FILE;
 # check parameters
 
 if [ -z "$DIR_SHARE" ]; then
-	echo "DIR_SHARE not set";
-	exit 1;
+  echo "DIR_SHARE not set";
+  exit 1;
 fi
 echo "Samba share mount point: $DIR_SHARE";
 
 if [ -z "$DIR_IMAGE" ]; then
-	echo "DIR_IMAGE not set";
-	exit 1;
+  echo "DIR_IMAGE not set";
+  exit 1;
 fi
 echo "Image file mount point : $DIR_IMAGE";
 
 if [ -z "$LOOPDEVICE" ]; then
-	echo "LOOPDEVICE not set";
-	exit 1;
+  echo "LOOPDEVICE not set";
+  exit 1;
 fi
 echo "Loop device: $LOOPDEVICE";
 
 if [ -z "$MAPPERNAME" ]; then
-	echo "MAPPERNAME not set";
-	exit 1;
+  echo "MAPPERNAME not set";
+  exit 1;
 fi
 echo "Device mapper: /dev/mapper/$MAPPERNAME";
 
 if [ -z "$SAMBA_USER" ]; then
-	echo "SAMBA_USER not set";
-	exit 1;
+  echo "SAMBA_USER not set";
+  exit 1;
 fi
 echo "Samba user: $SAMBA_USER";
 
 if [ -z "$SAMBA_PASSWORD" ]; then
-	echo "SAMBA_PASSWORD not set";
-	exit 1;
+  echo "SAMBA_PASSWORD not set";
+  exit 1;
 fi
 
 if [ -z "$SAMBA_PATH_SHARE" ]; then
-	echo "SAMBA_PATH_SHARE not set";
-	exit 1;
+  echo "SAMBA_PATH_SHARE not set";
+  exit 1;
 fi
 echo "Samba share path: $SAMBA_PATH_SHARE";
 
 if [ -z "$SAMBA_PATH_IMAGE" ]; then
-	echo "SAMBA_PATH_IMAGE not set";
-	exit 1;
+  echo "SAMBA_PATH_IMAGE not set";
+  exit 1;
 fi
 echo "Samba image path inside Samba share: $SAMBA_PATH_IMAGE";
 
 # make sure outer container dir is there
 echo "Checking share dir: $DIR_SHARE";
 if [ ! -d "$DIR_SHARE" ]; then
-	# make a dir to mount on
-	echo "Creating outer mount dir: $DIR_SHARE";
-	mkdir -p $DIR_SHARE
-	if [[ $? != 0 ]]; then
-		echo "Failed creating dir: $DIR_SHARE";
-		exit 1;
-	fi
+  # make a dir to mount on
+  echo "Creating outer mount dir: $DIR_SHARE";
+  mkdir -p $DIR_SHARE
+  if [[ $? != 0 ]]; then
+    echo "Failed creating dir: $DIR_SHARE";
+    exit 1;
+  fi
 fi
 
 # mount the outer cifs bridge over samba
 echo "Mounting samba share $SAMBA_PATH_SHARE to share dir $DIR_SHARE";
 mount -t cifs -o username=$SAMBA_USER,password=$SAMBA_PASSWORD //$SAMBA_PATH_SHARE $DIR_SHARE
 if [[ $? != 0 ]]; then
-	echo "Failed mounting samba share: $SAMBA_PATH_SHARE -> $DIR_SHARE";
-	exit 1;
+  echo "Failed mounting samba share: $SAMBA_PATH_SHARE -> $DIR_SHARE";
+  exit 1;
 fi
 
 # connecting loop device to image
 echo "Connecting $LOOPDEVICE to $DIR_SHARE$SAMBA_PATH_IMAGE";
 losetup $LOOPDEVICE $DIR_SHARE$SAMBA_PATH_IMAGE
 if [[ $? != 0 ]]; then
-	echo "Failed mounting dir: $DIR_SHARE$SAMBA_PATH_IMAGE";
-	exit 1;
+  echo "Failed mounting dir: $DIR_SHARE$SAMBA_PATH_IMAGE";
+  exit 1;
 fi
 
 # open loop device
@@ -123,21 +124,21 @@ cryptsetup luksOpen $LOOPDEVICE $MAPPERNAME
 # check the image dir
 echo "Checking image dir: $DIR_IMAGE";
 if [ ! -d "$DIR_IMAGE" ]; then
-	# make a dir to mount on
-	echo "Creating outer mount dir: $DIR_IMAGE";
-	mkdir -p $DIR_IMAGE
-	if [[ $? != 0 ]]; then
-		echo "Failed creating dir: $DIR_IMAGE";
-		exit 1;
-	fi
+  # make a dir to mount on
+  echo "Creating outer mount dir: $DIR_IMAGE";
+  mkdir -p $DIR_IMAGE
+  if [[ $? != 0 ]]; then
+    echo "Failed creating dir: $DIR_IMAGE";
+    exit 1;
+  fi
 fi
 
 # mount the image
 echo "Mounting mapper /dev/mapper/$MAPPERNAME to image dir $DIR_IMAGE";
 mount /dev/mapper/$MAPPERNAME $DIR_IMAGE
 if [[ $? != 0 ]]; then
-	echo "Failed mounting dir: $DIR_IMAGE";
-	exit 1;
+  echo "Failed mounting dir: $DIR_IMAGE";
+  exit 1;
 fi
 
 echo "Image is now ready in $DIR_IMAGE";
diff --git a/backup-sync b/backup-sync
--- a/backup-sync
+++ b/backup-sync
@@ -7,11 +7,13 @@
 # changelog
 # 2015-06-06 12:47:39
 # 2018-06-28 13:32:00 - cleanup
+# 2018-06-28 15:48:11
+# 2018-07-19 19:29:29 - indentation change, tab to 2 spaces
 
 # make sure only root can run our script
 if [[ $EUID -ne 0 ]]; then
-	echo "This script must be run as root";
-	exit 1;
+  echo "This script must be run as root";
+  exit 1;
 fi
 
 CONFIG_FILE="/etc/dptools/backuptools";
@@ -20,8 +22,8 @@ CONFIG_FILE="/etc/dptools/backuptools";
 DIR_IMAGE="/mnt/backupimage";
 
 if [ ! -f "$CONFIG_FILE" ]; then
-	echo "Missing configuration file: $CONFIG_FILE";
-	exit 1;
+  echo "Missing configuration file: $CONFIG_FILE";
+  exit 1;
 fi
 
 source $CONFIG_FILE;
@@ -29,8 +31,8 @@ source $CONFIG_FILE;
 echo "Checking if $DIR_IMAGE is mounted";
 mountpoint $DIR_IMAGE
 if [[ $? != 0 ]]; then
-	echo "$DIR_IMAGE is not mounted, something is wrong.";
-	exit 1;
+  echo "$DIR_IMAGE is not mounted, something is wrong.";
+  exit 1;
 fi
 
 # correct slash
@@ -39,46 +41,46 @@ DIR_IMAGE="$DIR_IMAGE/";
 echo "Running rsyncs";
 
 if [ -n "$SYNC_CMD1" ]; then
-	echo "Running sync: $SYNC_CMD1";
-	$SYNC_CMD1
-	if [[ $? != 0 ]]; then
-	echo "Sync failed will not continue";
-	exit 1;
-	fi
+  echo "Running sync: $SYNC_CMD1";
+  $SYNC_CMD1
+  if [[ $? != 0 ]]; then
+  echo "Sync failed will not continue";
+  exit 1;
+  fi
 fi
 
 if [ -n "$SYNC_CMD2" ]; then
-	echo "Running sync: $SYNC_CMD2";
-	$SYNC_CMD2
-	if [[ $? != 0 ]]; then
-	echo "Sync failed will not continue";
-	exit 1;
-	fi
+  echo "Running sync: $SYNC_CMD2";
+  $SYNC_CMD2
+  if [[ $? != 0 ]]; then
+  echo "Sync failed will not continue";
+  exit 1;
+  fi
 fi
 
 if [ -n "$SYNC_CMD3" ]; then
-	echo "Running sync: $SYNC_CMD3";
-	$SYNC_CMD3
-	if [[ $? != 0 ]]; then
-	echo "Sync failed will not continue";
-	exit 1;
-	fi
+  echo "Running sync: $SYNC_CMD3";
+  $SYNC_CMD3
+  if [[ $? != 0 ]]; then
+  echo "Sync failed will not continue";
+  exit 1;
+  fi
 fi
 
 if [ -n "$SYNC_CMD4" ]; then
-	echo "Running sync: $SYNC_CMD4";
-	$SYNC_CMD4
-	if [[ $? != 0 ]]; then
-	echo "Sync failed will not continue";
-	exit 1;
-	fi
+  echo "Running sync: $SYNC_CMD4";
+  $SYNC_CMD4
+  if [[ $? != 0 ]]; then
+  echo "Sync failed will not continue";
+  exit 1;
+  fi
 fi
 
 if [ -n "$SYNC_CMD5" ]; then
-	echo "Running sync: $SYNC_CMD5";
-	$SYNC_CMD5
-	if [[ $? != 0 ]]; then
-	echo "Sync failed will not continue";
-	exit 1;
-	fi
+  echo "Running sync: $SYNC_CMD5";
+  $SYNC_CMD5
+  if [[ $? != 0 ]]; then
+  echo "Sync failed will not continue";
+  exit 1;
+  fi
 fi
diff --git a/backup-umount b/backup-umount
--- a/backup-umount
+++ b/backup-umount
@@ -7,6 +7,7 @@
 # 2014-11-05 14:43:27 - initial version
 # 2015-06-06 12:38:51 - updated version for dptools
 # 2018-06-28 15:53:00 - cleanup
+# 2018-07-19 19:29:29 - indentation change, tab to 2 spaces
 
 # credentials
 DIR_IMAGE="/mnt/backupimage";
@@ -17,8 +18,8 @@ MAPPERNAME="backuploop";
 CONFIG_FILE="/etc/dptools/backuptools";
 
 if [ ! -f "$CONFIG_FILE" ]; then
-	echo "Missing configuration file: $CONFIG_FILE";
-	exit 1;
+  echo "Missing configuration file: $CONFIG_FILE";
+  exit 1;
 fi
 
 source $CONFIG_FILE;
@@ -33,32 +34,32 @@ fi
 echo "Unmounting image dir: $DIR_IMAGE";
 umount $DIR_IMAGE;
 if [[ $? != 0 ]]; then
-	echo "Failed unmounting dir: $DIR_IMAGE";
-	exit 1;
+  echo "Failed unmounting dir: $DIR_IMAGE";
+  exit 1;
 fi
 
 # close the luks mapping
 echo "Closing LUKS mapper: /dev/mapper/$MAPPERNAME";
 cryptsetup luksClose /dev/mapper/$MAPPERNAME
 if [[ $? != 0 ]]; then
-	echo "Failed closing LUKS mapper: /dev/mapper/$MAPPERNAME";
-	exit 1;
+  echo "Failed closing LUKS mapper: /dev/mapper/$MAPPERNAME";
+  exit 1;
 fi
 
 # delete the loop device
 echo "Deleting loop device: $LOOPDEVICE";
 losetup -d $LOOPDEVICE
 if [[ $? != 0 ]]; then
-	echo "Failed deleting loop device: $LOOPDEVICE";
-	exit 1;
+  echo "Failed deleting loop device: $LOOPDEVICE";
+  exit 1;
 fi
 
 # unmount the share dir
 echo "Unmounting share dir: $DIR_SHARE";
 umount $DIR_SHARE
 if [[ $? != 0 ]]; then
-	echo "Failed unmounting dir: $DIR_SHARE";
-	exit 1;
+  echo "Failed unmounting dir: $DIR_SHARE";
+  exit 1;
 fi
 
 # tell that it went fine
diff --git a/dptools-update b/dptools-update
--- a/dptools-update
+++ b/dptools-update
@@ -15,6 +15,7 @@
 # 2018-06-29 19:20:00 - bugfix, update failed to run
 # 2018-06-30 02:25:00 - adding support for arguments and user profile files editing
 # 2018-07-01 14:11:00 - adding git installer
+# 2018-07-19 19:29:30 - indentation change, tab to 2 spaces
 
 ACTION_ADD="";
 ACTION_UPDATE="";
@@ -23,208 +24,208 @@ CURRENTUSER=$(whoami);
 TARGETDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)";
 
 while getopts ":ahuy" opt; do
-	case $opt in
-		a) # add to provided or current user
+  case $opt in
+    a) # add to provided or current user
 
-			# read optional argument
-			OPTARG=${!OPTIND}
-			if [ "${OPTARG:0:1}" == "-" ] || [ "$#" -lt "$OPTIND" ]; then
-				# default value if nothing is set
-				OPTARG=$CURRENTUSER;
-			else
-				OPTIND=$(( $OPTIND + 1 ))
-			fi
+      # read optional argument
+      OPTARG=${!OPTIND}
+      if [ "${OPTARG:0:1}" == "-" ] || [ "$#" -lt "$OPTIND" ]; then
+        # default value if nothing is set
+        OPTARG=$CURRENTUSER;
+      else
+        OPTIND=$(( $OPTIND + 1 ))
+      fi
 
-			ACTION_ADD=$OPTARG;
-			;;
+      ACTION_ADD=$OPTARG;
+      ;;
 
-		h) # print help
+    h) # print help
 cat << EOF
 Update dptools.
 
 Usage: dptools-update [-a [user]][-h][-u][-y]
 
 -a [username - defaults to current user]
-	Add dptools-console-init call to .bashrc and .profile
-	for current user or for the user provided in the argument.
+  Add dptools-console-init call to .bashrc and .profile
+  for current user or for the user provided in the argument.
 
 -h
-	Print this information and exit.
+  Print this information and exit.
 
 -u
-	Update dptools. Uses git pull. This is the default action
-	unless any other parameter is given.
+  Update dptools. Uses git pull. This is the default action
+  unless any other parameter is given.
 
 -y
-	Answer yes on confirmation questions.
+  Answer yes on confirmation questions.
 
 EOF
-			exit 0;
-			;;
+      exit 0;
+      ;;
 
-		u) # update
-			ACTION_UPDATE="1";
-			;;
+    u) # update
+      ACTION_UPDATE="1";
+      ;;
 
-		y) # param force yes
-			PARAM_FORCE_YES="1";
-			;;
-		\?)
-			echo "Error: invalid option -$OPTARG" >&2;
-			exit 1;
-			;;
-	esac
+    y) # param force yes
+      PARAM_FORCE_YES="1";
+      ;;
+    \?)
+      echo "Error: invalid option -$OPTARG" >&2;
+      exit 1;
+      ;;
+  esac
 done
 
 # no option given at all?
 if [ -z $ACTION_ADD ] && [ -z $ACTION_DEPRECATED ] && [ -z $ACTION_UPDATE ]; then
-	# run update
-	ACTION_UPDATE="1";
+  # run update
+  ACTION_UPDATE="1";
 fi
 
 # action: update
 if [[ "$ACTION_UPDATE" == "1" ]]; then
-	if ! [ -x "$(command -v git)" ]; then
-		if [[ ! $CURRENTUSER == "root" ]]; then
-			echo "Error: git is not installed and you are not root, so cannot try to install either. Try again as root." >&2;
-			exit 1;
-		fi
+  if ! [ -x "$(command -v git)" ]; then
+    if [[ ! $CURRENTUSER == "root" ]]; then
+      echo "Error: git is not installed and you are not root, so cannot try to install either. Try again as root." >&2;
+      exit 1;
+    fi
 
-		if [ ! -x "$(command -v 'apt-get')" ]; then
-			echo "Error: git is not installed, cannot install because apt-get command is not available. Install git and retry.";
-			exit 1;
-		fi
+    if [ ! -x "$(command -v 'apt-get')" ]; then
+      echo "Error: git is not installed, cannot install because apt-get command is not available. Install git and retry.";
+      exit 1;
+    fi
 
-		if [[ $PARAM_FORCE_YES != "1" ]]; then
-			read -p "Git is not installed and it is needed, install it? [y or n]: " -n 1 -r
-			if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-				exit 1;
-			fi
-		fi
+    if [[ $PARAM_FORCE_YES != "1" ]]; then
+      read -p "Git is not installed and it is needed, install it? [y or n]: " -n 1 -r
+      if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+        exit 1;
+      fi
+    fi
 
-		apt-get install -y git
-		if [ ! $? -eq 0 ]; then
-			echo 'Error: failed to install git.' >&2;
-			exit 1;
-		fi
+    apt-get install -y git
+    if [ ! $? -eq 0 ]; then
+      echo 'Error: failed to install git.' >&2;
+      exit 1;
+    fi
 
-		if [ ! -x "$(command -v 'apt-get')" ]; then
-			echo "Error: git is still not installed.";
-			exit 1;
-		fi
-	fi
+    if [ ! -x "$(command -v 'apt-get')" ]; then
+      echo "Error: git is still not installed.";
+      exit 1;
+    fi
+  fi
 
-	if [[ -z $TARGETDIR	]]; then
-		echo "Errr: could not find target directory $TARGETDIR." >&2;
-		exit 1;
-	fi
+  if [[ -z $TARGETDIR	]]; then
+    echo "Errr: could not find target directory $TARGETDIR." >&2;
+    exit 1;
+  fi
 
-	echo "dptools directory: $TARGETDIR";
+  echo "dptools directory: $TARGETDIR";
 
-	if [ ! -w $TARGETDIR ] ; then
-		echo "Error: dptools directory $TARGETDIR is not writable for your user." >&2;
-		exit 1;
-	fi
+  if [ ! -w $TARGETDIR ] ; then
+    echo "Error: dptools directory $TARGETDIR is not writable for your user." >&2;
+    exit 1;
+  fi
 
-	# does target dir exist
-	if [ -d "$TARGETDIR" ]; then
-		cd "$TARGETDIR";
-		git pull
-		if [ ! $? -eq 0 ]; then
-			echo 'Error: failed pulling data from git repository.' >&2;
-			exit 1;
-		fi
-	fi
+  # does target dir exist
+  if [ -d "$TARGETDIR" ]; then
+    cd "$TARGETDIR";
+    git pull
+    if [ ! $? -eq 0 ]; then
+      echo 'Error: failed pulling data from git repository.' >&2;
+      exit 1;
+    fi
+  fi
 
-	# does target dir not exist
-	if [ ! -d "$TARGETDIR" ]; then
-		git clone https://gitlab.com/dotpointer/dptools.git $TARGETDIR
-		if [ ! $? -eq 0 ]; then
-			echo 'Error: failed cloning data from git repository.' >&2;
-			exit 1;
-		fi
-	fi
+  # does target dir not exist
+  if [ ! -d "$TARGETDIR" ]; then
+    git clone https://gitlab.com/dotpointer/dptools.git $TARGETDIR
+    if [ ! $? -eq 0 ]; then
+      echo 'Error: failed cloning data from git repository.' >&2;
+      exit 1;
+    fi
+  fi
 
-	# end message
-	echo "Update finished, thank you for using dptools."
+  # end message
+  echo "Update finished, thank you for using dptools."
 fi
 
 # action: add dptools to user profile
 if [[ ! -z $ACTION_ADD ]]; then
-	# get user home directory
-	HOMEDIR=$(getent passwd $ACTION_ADD | cut -d: -f6);
-	if [ ! $? -eq 0 ] ; then
-		echo "Error: failed removing deprecated file $REMOVEFILE";
-		exit 1;
-	fi
+  # get user home directory
+  HOMEDIR=$(getent passwd $ACTION_ADD | cut -d: -f6);
+  if [ ! $? -eq 0 ] ; then
+    echo "Error: failed removing deprecated file $REMOVEFILE";
+    exit 1;
+  fi
 
-	if [[ -z $HOMEDIR ]]; then
-		echo "Error: could not find home directory for user $ACTION_ADD";
-		exit 1;
-	fi
+  if [[ -z $HOMEDIR ]]; then
+    echo "Error: could not find home directory for user $ACTION_ADD";
+    exit 1;
+  fi
 
-	if [[ ! -d $HOMEDIR ]]; then
-		echo "Error: home directory $HOMEDIR does not exist.";
-		exit 1;
-	fi
+  if [[ ! -d $HOMEDIR ]]; then
+    echo "Error: home directory $HOMEDIR does not exist.";
+    exit 1;
+  fi
 
-	# look for this line
-	NEEDEDLINE=". $TARGETDIR/dptools-console-init";
+  # look for this line
+  NEEDEDLINE=". $TARGETDIR/dptools-console-init";
 
-	# loop through files to check for dptools-console-init in them
-	declare -a items=(".bashrc" ".profile")
-	for i in "${items[@]}"
-	do
-		# get current fullpath
-		CURRENTFILE="$HOMEDIR/$i";
+  # loop through files to check for dptools-console-init in them
+  declare -a items=(".bashrc" ".profile")
+  for i in "${items[@]}"
+  do
+    # get current fullpath
+    CURRENTFILE="$HOMEDIR/$i";
 
-		# is current file not existing
-		if [[ ! -f $CURRENTFILE ]]; then
-			# is there no write access to the home directory
-			if [[ ! -w $HOMEDIR ]]; then
-				echo "Error: no write access for home directory $HOMEDIR.";
-				exit 1;
-			fi
-			echo "$CURRENTFILE does not exist, trying to touch it.";
-			touch $CURRENTFILE;
-			if [ $? -ne 0 ]; then
-				echo "Error: failed touching $CURRENTFILE";
-			fi
-		fi
+    # is current file not existing
+    if [[ ! -f $CURRENTFILE ]]; then
+      # is there no write access to the home directory
+      if [[ ! -w $HOMEDIR ]]; then
+        echo "Error: no write access for home directory $HOMEDIR.";
+        exit 1;
+      fi
+      echo "$CURRENTFILE does not exist, trying to touch it.";
+      touch $CURRENTFILE;
+      if [ $? -ne 0 ]; then
+        echo "Error: failed touching $CURRENTFILE";
+      fi
+    fi
 
-		# is current file not existing or writeable
-		if [ ! -f $CURRENTFILE ] ; then
-			echo "Error: $CURRENTFILE does not exist.";
-		# or is current file existing and writeable
-		else
-			# look in file for the needed line
-			DATA=$(cat $CURRENTFILE|grep "$NEEDEDLINE");
-			# was the line missing
-			if [[ -z $DATA ]]; then
-				# is the file writeable
-				if [[ -w $CURRENTFILE ]]; then
-					# try to add the line
-					echo "$CURRENTFILE is missing dptools-console-init, trying to add it";
-					echo $NEEDEDLINE >> $CURRENTFILE;
-					if [ $? -ne 0 ]; then
-						echo "Error: failed adding dptools-console-init to $CURRENTFILE";
-						# no exit here, take next file
-					else
-						# is this the profile file and the user is the current one
-						if [ "$i" == ".profile" ] && [ "$ACTION_ADD" == "$CURRENTUSER" ]; then
-							# then reload the profile
-							echo "Reloading current user profile.";
-							source "$HOMEDIR/.profile";
-						fi
-					fi
-				# or is the file not writeable
-				else
-					echo "Error: $CURRENTFILE is missing dptools-console-init, but file is not writeable.";
-					# no exit here, take next file
-				fi
-			else
-				echo "$CURRENTFILE already seems to have dptools-console-init";
-			fi
-		fi
-	done
+    # is current file not existing or writeable
+    if [ ! -f $CURRENTFILE ] ; then
+      echo "Error: $CURRENTFILE does not exist.";
+    # or is current file existing and writeable
+    else
+      # look in file for the needed line
+      DATA=$(cat $CURRENTFILE|grep "$NEEDEDLINE");
+      # was the line missing
+      if [[ -z $DATA ]]; then
+        # is the file writeable
+        if [[ -w $CURRENTFILE ]]; then
+          # try to add the line
+          echo "$CURRENTFILE is missing dptools-console-init, trying to add it";
+          echo $NEEDEDLINE >> $CURRENTFILE;
+          if [ $? -ne 0 ]; then
+            echo "Error: failed adding dptools-console-init to $CURRENTFILE";
+            # no exit here, take next file
+          else
+            # is this the profile file and the user is the current one
+            if [ "$i" == ".profile" ] && [ "$ACTION_ADD" == "$CURRENTUSER" ]; then
+              # then reload the profile
+              echo "Reloading current user profile.";
+              source "$HOMEDIR/.profile";
+            fi
+          fi
+        # or is the file not writeable
+        else
+          echo "Error: $CURRENTFILE is missing dptools-console-init, but file is not writeable.";
+          # no exit here, take next file
+        fi
+      else
+        echo "$CURRENTFILE already seems to have dptools-console-init";
+      fi
+    fi
+  done
 fi
diff --git a/vmcpus b/vmcpus
--- a/vmcpus
+++ b/vmcpus
@@ -9,39 +9,40 @@
 # 2015-07-19 00:03:00 - vmcap, adding listing when no name is given
 # 2018-01-16 18:03:00 - converting vmcap to vpcpus
 # 2018-06-29 16:27:00 - cleanup
+# 2018-07-19 19:29:34 - indentation change, tab to 2 spaces
 
 NAME=$1
 PARAM=$2
 
 # is name given?
 if [ -z "$NAME" ]; then
-	# echo "Name of VM must be given, path to disk can be given.";
+  # echo "Name of VM must be given, path to disk can be given.";
 
-	VMS=$(VBoxManage list vms);
+  VMS=$(VBoxManage list vms);
 
-	# list the vms, cut out the name of the vms and then sort the strings
-	arr=$(VBoxManage list vms|sed -rn 's/^\"(.*)\"( \{[a-z0-9\-]+\})/\1  /p'|sort)
+  # list the vms, cut out the name of the vms and then sort the strings
+  arr=$(VBoxManage list vms|sed -rn 's/^\"(.*)\"( \{[a-z0-9\-]+\})/\1  /p'|sort)
 
-	# walk the lines
-	for x in $arr
-	do
-		# print the lines
-		echo $x $(vminfo "$x"|grep "Number of CPUs")
-	done;
+  # walk the lines
+  for x in $arr
+  do
+    # print the lines
+    echo $x $(vminfo "$x"|grep "Number of CPUs")
+  done;
 
-	exit 1
+  exit 1
 fi
 
 # no parameter given?
 if [ -z "$PARAM" ]; then
-	vminfo "$NAME"|grep "Number of CPUs"
-	exit 0
+  vminfo "$NAME"|grep "Number of CPUs"
+  exit 0
 fi
 
 # list and scan for VM:s
 VMS=$(VBoxManage list vms)
 if [[ ! $VMS == *"$1"* ]]; then
-	echo "VM $1 not found.";
+  echo "VM $1 not found.";
 fi
 
 echo "Setting $NAME:s number of CPUs to $PARAM";
diff --git a/vmdel b/vmdel
--- a/vmdel
+++ b/vmdel
@@ -7,21 +7,22 @@
 # changelog
 # 2014-10-01 12:08:46
 # 2018-06-29 16:30:00 - cleanup
+# 2018-07-19 19:29:34 - indentation change, tab to 2 spaces
 
 if [ -z "$1" ]; then
-	echo "Name of VM must be given";
-	exit 1
+  echo "Name of VM must be given";
+  exit 1
 fi
 
 # list and scan for VM:s
 VMS=$(VBoxManage list vms)
 if [[ ! $VMS == *"$1"* ]]; then
-	echo "VM $1 not found.";
-	exit 1
+  echo "VM $1 not found.";
+  exit 1
 fi
 
 echo "This will delete VM $1, press enter to continue..."
 read
 if [ -n "$1" ]; then
-	VBoxManage unregistervm $1 --delete
+  VBoxManage unregistervm $1 --delete
 fi
diff --git a/vmfloppy b/vmfloppy
--- a/vmfloppy
+++ b/vmfloppy
@@ -7,22 +7,23 @@
 # changelog
 # 2014-10-01 12:09:34
 # 2018-06-29 16:34:00
+# 2018-07-19 19:29:34 - indentation change, tab to 2 spaces
 
 NAME=$1
 MEDIUM=$2
 if [ -z "$NAME" ]; then
-	echo "Name of VM must be given, path to disk can be given.";
-	exit 1
+  echo "Name of VM must be given, path to disk can be given.";
+  exit 1
 fi
 
 if [ -z "$MEDIUM" ]; then
-	MEDIUM='emptydrive'
+  MEDIUM='emptydrive'
 fi
 
 # list and scan for VM:s
 VMS=$(VBoxManage list vms)
 if [[ ! $VMS == *"$1"* ]]; then
-	echo "VM $1 not found.";
+  echo "VM $1 not found.";
 fi
 
 VBoxManage storageattach "$NAME" --storagectl "FDD Controller" --port 0 --device 0 --type fdd --medium $MEDIUM
diff --git a/vmnew b/vmnew
--- a/vmnew
+++ b/vmnew
@@ -11,17 +11,18 @@
 # 2018-06-09 10:52:00 - replacing network interface eth1 with eth0
 # 2018-06-29 16:52:00 - cleanup
 # 2018-06-29 18:39:00 - bugfix, disk storage location was hardcoded
+# 2018-07-19 19:29:35 - indentation change, tab to 2 spaces
 
 if [ ! -f /etc/dptools/virtualbox ]; then
-	echo 'Please create /etc/dptools/virtualbox and add VIRTUALBOX_ROOT_DIR="/where/to/store/harddrives/"';
-	exit 1;
+  echo 'Please create /etc/dptools/virtualbox and add VIRTUALBOX_ROOT_DIR="/where/to/store/harddrives/"';
+  exit 1;
 fi
 
 source /etc/dptools/virtualbox
 
 if [ -z ${VIRTUALBOX_ROOT_DIR+x} ]; then
-	echo 'Please add VIRTUALBOX_ROOT_DIR="/where/to/store/harddrives/" to /etc/dptools/virtualbox';
-	exit 1;
+  echo 'Please add VIRTUALBOX_ROOT_DIR="/where/to/store/harddrives/" to /etc/dptools/virtualbox';
+  exit 1;
 fi
 
 # ask for name
@@ -31,15 +32,15 @@ read NAME;
 
 # make sure it is entered
 if [ -z "$NAME" ]; then
-	echo "Must be given, quitting.";
-	exit 1;
+  echo "Must be given, quitting.";
+  exit 1;
 fi
 
 # list and scan for VM:s
 VMS=$(VBoxManage list vms)
 if [[ $VMS == *"$NAME"* ]]; then
-	echo "VM $NAME already exists, quitting.";
-	exit 1;
+  echo "VM $NAME already exists, quitting.";
+  exit 1;
 fi
 
 # ask for OS type
@@ -53,7 +54,7 @@ read OSTYPE
 
 # make sure it is entered
 if [ -z "$OSTYPE" ]; then
-	OSTYPE=$DEFAULT_OSTYPE;
+  OSTYPE=$DEFAULT_OSTYPE;
 fi
 
 # ask for hardware setup
@@ -64,7 +65,7 @@ DEFAULT_MEMORY=256;
 echo -ne "- RAM in MB ($DEFAULT_MEMORY): ";
 read MEMORY
 if [ -z "$MEMORY" ]; then
-	MEMORY=$DEFAULT_MEMORY;
+  MEMORY=$DEFAULT_MEMORY;
 fi
 
 # VRAM
@@ -72,7 +73,7 @@ DEFAULT_VRAM=128;
 echo -ne "- VRAM in MB ($DEFAULT_VRAM): ";
 read VRAM
 if [ -z "$VRAM" ]; then
-	VRAM=$DEFAULT_VRAM;
+  VRAM=$DEFAULT_VRAM;
 fi
 
 # RAM
@@ -80,7 +81,7 @@ DEFAULT_CPUCAP=50;
 echo -ne "- Max CPU% usage ($DEFAULT_CPUCAP): ";
 read CPUCAP
 if [ -z "$CPUCAP" ]; then
-	CPUCAP=$DEFAULT_CPUCAP;
+  CPUCAP=$DEFAULT_CPUCAP;
 fi
 
 # Disk
@@ -92,7 +93,7 @@ DEFAULT_VRDEPORT=3390;
 echo -ne "- VRDE port in MB ($DEFAULT_VRDEPORT): "
 read VRDEPORT
 if [ -z "$VRDEPORT" ]; then
-	VRDEPORT=$DEFAULT_VRDEPORT
+  VRDEPORT=$DEFAULT_VRDEPORT
 fi
 
 echo "--- Ready to create new VM"
@@ -111,83 +112,83 @@ read -p "- Press enter to create " -n 1
 echo "-- Trying to create VM: $NAME...";
 VBoxManage createvm --name "$NAME" --ostype $OSTYPE --register
 if [ ! $? -eq 0 ] ; then
-	echo 'Failed';
-	exit 1
+  echo 'Failed';
+  exit 1
 fi
 
 # try to setup machine hardware specs, accelerate 3d = off since 4.2
 echo "-- Trying to set hardware specifications...";
 VBoxManage modifyvm "$NAME" --memory $MEMORY --acpi on --boot1 dvd --nic1 bridged --bridgeadapter1 eth0 --nictype1 "82540EM" --vrde on --vrdeauthtype null --vrdemulticon on --vram $VRAM --accelerate3d off --cpuexecutioncap $CPUCAP --vrdeport $VRDEPORT --pae on --chipset ich9 --ioapic on --firmware bios
 if [ ! $? -eq 0 ] ; then
-	echo 'Failed';
-	exit 1
+  echo 'Failed';
+  exit 1
 fi
 
 # try to add storage controller
 echo "-- Trying to add storage controller...";
 VBoxManage storagectl "$NAME" --name "SATA Controller" --add sata --controller IntelAHCI
 if [ ! $? -eq 0 ] ; then
-	echo 'Failed';
-	exit 1
+  echo 'Failed';
+  exit 1
 fi
 
 # DVD drive
 echo "-- Trying to add DVD drive...";
 VBoxManage storageattach "$NAME" --storagectl "SATA Controller" --port 1 --device 0 --type dvddrive --medium emptydrive
 if [ ! $? -eq 0 ] ; then
-	echo 'Failed';
-	exit 1
+  echo 'Failed';
+  exit 1
 fi
 
 # if disk is requested
 if [ -n "$DISKSIZE" ]; then
-	# try to create disk
-	echo "-- Trying to create disk...";
-	VBoxManage createhd --filename "$VIRTUALBOX_ROOT_DIR$NAME/$NAME.vdi" --size $DISKSIZE
-	if [ ! $? -eq 0 ] ; then
-		 echo "Failed";
-		 exit 1
-	fi
+  # try to create disk
+  echo "-- Trying to create disk...";
+  VBoxManage createhd --filename "$VIRTUALBOX_ROOT_DIR$NAME/$NAME.vdi" --size $DISKSIZE
+  if [ ! $? -eq 0 ] ; then
+     echo "Failed";
+     exit 1
+  fi
 
-	# try to attach disk
-	echo "-- Trying to attach disk...";
-	VBoxManage storageattach "$NAME" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "$VIRTUALBOX_ROOT_DIR$NAME/$NAME.vdi"
-	if [ ! $? -eq 0 ] ; then
-		 echo "Failed";
-		 exit 1
-	fi
+  # try to attach disk
+  echo "-- Trying to attach disk...";
+  VBoxManage storageattach "$NAME" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "$VIRTUALBOX_ROOT_DIR$NAME/$NAME.vdi"
+  if [ ! $? -eq 0 ] ; then
+     echo "Failed";
+     exit 1
+  fi
 fi
 
 # AUDIO
 echo "-- Trying to add audio ALSA / AC97";
 VBoxManage modifyvm "$NAME" --audio alsa --audiocontroller ac97
 if [ ! $? -eq 0 ] ; then
-	echo "Failed";
-	exit 1
+  echo "Failed";
+  exit 1
 fi
 
 # USB controller
 echo "-- Trying to enable USB controller";
 VBoxManage modifyvm "$NAME" --usb on
 if [ ! $? -eq 0 ] ; then
-	echo "Failed";
-	exit 1
+  echo "Failed";
+  exit 1
 fi
 
 # USB 2.0 controller
 echo "-- Trying to enable USB 2.0 controller";
 VBoxManage modifyvm "$NAME" --usbehci on
 if [ ! $? -eq 0 ] ; then
-	echo "Failed";
-	exit 1
+  echo "Failed";
+  exit 1
 fi
 
 # USB 3.0 controller
 echo "-- Trying to enable USB 3.0 controller";
 VBoxManage modifyvm "$NAME" --usbxhci on
 if [ ! $? -eq 0 ] ; then
-	echo "Failed";
-	exit 1
+  echo "Failed";
+  exit 1
 fi
 
 echo "--- Creation of $NAME is complete.";
