Major cleanup for repository publication continued.

diff --git a/pdfgreyscale b/pdfgreyscale
--- a/pdfgreyscale
+++ b/pdfgreyscale
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+# pdfgreyscale
 # make pdf files greyscale
 # by robert klebe, dotpointer
 
@@ -7,6 +8,7 @@
 # 2015-10-15 11:23:18
 # 2017-02-05 14:25:00 - updating with checks and optional output name
 # 2017-02-05 15:52:00 - updating meta data with creation date set to original file
+# 2018-06-29 14:18:00 - cleanup
 
 # check locales
 
@@ -20,8 +22,8 @@ fi
 # no parameters
 if [ $# -eq 0 ]; then
 	# show help
-	echo "Usage: $0 input.pdf [output.pdf - defaults to input.greyscale.pdf]"
-	exit 1
+	echo "Usage: $0 input.pdf [output.pdf - defaults to input.greyscale.pdf]";
+	exit 1;
 fi
 
 # only 1 parameter
@@ -36,17 +38,17 @@ fi
 
 export LC_ALL=en_US.utf8;
 
-TMPPDF="/tmp/pdf_temp_file"
+TMPPDF="/tmp/pdf_temp_file";
 
 # store metadata
 pdftk "$1" dump_data_utf8 > "$OUTNAME.metadata"
 
 # get and format creation date
-CREATIONDATE=$(/bin/date +'%a %b %Oe %T %Y' -r "$1")
+CREATIONDATE=$(/bin/date +'%a %b %Oe %T %Y' -r "$1");
 # put this info to the metadata file
-echo "InfoBegin" >> $OUTNAME.metadata
-echo "InfoKey: CreationDate" >> $OUTNAME.metadata
-echo "InfoValue: $CREATIONDATE" >> $OUTNAME.metadata
+echo "InfoBegin" >> $OUTNAME.metadata;
+echo "InfoKey: CreationDate" >> $OUTNAME.metadata;
+echo "InfoValue: $CREATIONDATE" >> $OUTNAME.metadata;
 
 # run ghostscript
 gs -sOutputFile="$OUTNAME.temp" -sDEVICE=pdfwrite -sColorConversionStrategy=Gray -dProcessColorModel=/DeviceGray -dCompatibilityLevel=1.4 -dNOPAUSE -dBATCH "$1"
diff --git a/vmcap b/vmcap
--- a/vmcap
+++ b/vmcap
@@ -1,30 +1,34 @@
 #!/bin/bash
-# to set the cpu exec cap of virtual boxes
+
+# vmcap
+# virtualbox, get and set machine cpu cap
+# by robert klebe, dotpointer
 
 # changelog
 # 2014-10-01 12:08:02
 # 2015-07-19 00:03:00 - adding listing when no name is given
+# 2018-06-29 16:12:00 - cleanup
 
 NAME=$1
 PARAM=$2
 
 # is name given?
 if [ -z "$NAME" ]; then
-    # echo "Name of VM must be given, path to disk can be given.";
-    
-    VMS=$(VBoxManage list vms);
-    
-    # list the vms, cut out the name of the vms and then sort the strings
-    arr=$(VBoxManage list vms|sed -rn 's/^\"(.*)\"( \{[a-z0-9\-]+\})/\1  /p'|sort)
-    
-    # walk the lines
-    for x in $arr
-    do
-        # print the lines
-        echo $x $(vminfo "$x"|grep "exec cap")
-    done;
-    
-    exit 1
+	# echo "Name of VM must be given, path to disk can be given.";
+
+	VMS=$(VBoxManage list vms);
+
+	# list the vms, cut out the name of the vms and then sort the strings
+	arr=$(VBoxManage list vms|sed -rn 's/^\"(.*)\"( \{[a-z0-9\-]+\})/\1  /p'|sort)
+
+	# walk the lines
+	for x in $arr
+	do
+		# print the lines
+		echo $x $(vminfo "$x"|grep "exec cap")
+	done;
+
+	exit 1
 fi
 
 # no parameter given?
diff --git a/vmcd b/vmcd
--- a/vmcd
+++ b/vmcd
@@ -1,22 +1,28 @@
 #!/bin/bash
-# to insert and eject cd:s of a VM
+
+# vmcd
+# set machine optical SATA device disc
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 11:42:13
+# 2018-06-29 16:15:00 - cleanup
 
 NAME=$1
 MEDIUM=$2
 if [ -z "$NAME" ]; then
-    echo "Name of VM must be given, path to disk can be given.";
-    exit 1
+	echo "Name of VM must be given, path to disk can be given.";
+	exit 1;
 fi
 
 if [ -z "$MEDIUM" ]; then
-    MEDIUM='emptydrive'
+	MEDIUM='emptydrive'
 fi
 
 # list and scan for VM:s
 VMS=$(VBoxManage list vms)
 if [[ ! $VMS == *"$1"* ]]; then
-echo "VM $1 not found.";
+	echo "VM $1 not found.";
 fi
-
 
 VBoxManage storageattach "$NAME" --storagectl "SATA Controller" --port 1 --device 0 --type dvddrive --medium $MEDIUM
diff --git a/vmcpus b/vmcpus
--- a/vmcpus
+++ b/vmcpus
@@ -1,31 +1,35 @@
 #!/bin/bash
-# to set the cpu count of virtual boxes
+
+# vmcpus
+# virtualbox, get and set the number of machine cpu:s
+# by robert klebe, dotpointer
 
 # changelog
 # 2014-10-01 12:08:02 - vmcap
 # 2015-07-19 00:03:00 - vmcap, adding listing when no name is given
 # 2018-01-16 18:03:00 - converting vmcap to vpcpus
+# 2018-06-29 16:27:00 - cleanup
 
 NAME=$1
 PARAM=$2
 
 # is name given?
 if [ -z "$NAME" ]; then
-    # echo "Name of VM must be given, path to disk can be given.";
-    
-    VMS=$(VBoxManage list vms);
-    
-    # list the vms, cut out the name of the vms and then sort the strings
-    arr=$(VBoxManage list vms|sed -rn 's/^\"(.*)\"( \{[a-z0-9\-]+\})/\1  /p'|sort)
-    
-    # walk the lines
-    for x in $arr
-    do
-        # print the lines
-        echo $x $(vminfo "$x"|grep "Number of CPUs")
-    done;
-    
-    exit 1
+	# echo "Name of VM must be given, path to disk can be given.";
+
+	VMS=$(VBoxManage list vms);
+
+	# list the vms, cut out the name of the vms and then sort the strings
+	arr=$(VBoxManage list vms|sed -rn 's/^\"(.*)\"( \{[a-z0-9\-]+\})/\1  /p'|sort)
+
+	# walk the lines
+	for x in $arr
+	do
+		# print the lines
+		echo $x $(vminfo "$x"|grep "Number of CPUs")
+	done;
+
+	exit 1
 fi
 
 # no parameter given?
@@ -37,7 +41,7 @@ fi
 # list and scan for VM:s
 VMS=$(VBoxManage list vms)
 if [[ ! $VMS == *"$1"* ]]; then
-echo "VM $1 not found.";
+	echo "VM $1 not found.";
 fi
 
 echo "Setting $NAME:s number of CPUs to $PARAM";
diff --git a/vmdel b/vmdel
--- a/vmdel
+++ b/vmdel
@@ -1,8 +1,16 @@
 #!/bin/bash
 
+# vmdel
+# virtualbox, delete machine
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 12:08:46
+# 2018-06-29 16:30:00 - cleanup
+
 if [ -z "$1" ]; then
-    echo "Name of VM must be given";
-    exit 1
+	echo "Name of VM must be given";
+	exit 1
 fi
 
 # list and scan for VM:s
@@ -15,6 +23,5 @@ fi
 echo "This will delete VM $1, press enter to continue..."
 read
 if [ -n "$1" ]; then
-    VBoxManage unregistervm $1 --delete
+	VBoxManage unregistervm $1 --delete
 fi
-
diff --git a/vmdiskmount b/vmdiskmount
--- a/vmdiskmount
+++ b/vmdiskmount
@@ -1,8 +1,17 @@
 #!/bin/bash
 
+# vmdiskmount
+# virtualbox, mount machine ide device
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 12:09:00
+# 2018-06-29 16:31:00 - cleanup
+
+
 if [ -z "$1" ] || [ -z "$2" ]; then
-   echo "VM name and path to device (/dev/blahblah or 'none') must be given.";
-   exit 1
+	echo "VM name and path to device (/dev/example or 'none') must be given.";
+	exit 1
 fi
 
 VBoxManage storageattach "$1" --storagectl "IDE Controller" --port 1 --device 0 --type hdd --medium $2
diff --git a/vmmount b/vmmount
--- a/vmmount
+++ b/vmmount
@@ -1,8 +1,16 @@
 #!/bin/bash
 
+# vmmount
+# virtualbox, mount ide device
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 12:08:23
+# 2018-06-29 16:51:00 - cleanup
+
 if [ -z "$1" ] || [ -z "$2" ]; then
-   echo "VM name and path to device (/dev/blahblah or 'none') must be given.";
-   exit 1
+	echo "VM name and path to device (/dev/example or 'none') must be given.";
+	exit 1
 fi
 
 VBoxManage storageattach "$1" --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium $2
diff --git a/vmnew b/vmnew
--- a/vmnew
+++ b/vmnew
@@ -1,176 +1,180 @@
 #!/bin/bash
-# 2011-10-30 - VirtualBox VM creation script, by Robert Klebe
-# 2014-04-06 - improved with SATA, IO APIC, chipset ICH9
-# 2014-10-01 - cleanup
+
+# vmnew
+# virtualbox, create a new machine
+# by robert klebe, dotpointer
+
+# changelog
+# 2011-10-30 xx:xx:xx - VirtualBox VM creation script, by Robert Klebe
+# 2014-04-06 xx:xx:xx - improved with SATA, IO APIC, chipset ICH9
+# 2014-10-01 xx:xx:xx - cleanup
 # 2018-06-09 10:52:00 - replacing network interface eth1 with eth0
+# 2018-06-29 16:52:00 - cleanup
 
 # ask for name
-echo "--- Name of the new machine"
-echo -ne "- Name: "
-read NAME
+echo "--- Name of the new machine";
+echo -ne "- Name: ";
+read NAME;
 
 # make sure it is entered
-if [ -z "$NAME" ]; then 
-   echo "Must be given, quitting."
-   exit 1
+if [ -z "$NAME" ]; then
+	echo "Must be given, quitting.";
+	exit 1;
 fi
 
 # list and scan for VM:s
 VMS=$(VBoxManage list vms)
 if [[ $VMS == *"$NAME"* ]]; then
-   echo "VM $NAME already exists, quitting.";
-   exit 1
+	echo "VM $NAME already exists, quitting.";
+	exit 1;
 fi
 
 # ask for OS type
-echo "--- OS type for the new machine"
+echo "--- OS type for the new machine";
 DEFAULT_OSTYPE="Other";
-echo -ne "Must be one of these: "
-VBoxManage list ostypes|grep ID|tr -d 'ID:          '| tr '\n' ", "; 
+echo -ne "Must be one of these: ";
+VBoxManage list ostypes|grep ID|tr -d 'ID:			'| tr '\n' ", ";
 echo
-echo -ne "- OS type ($DEFAULT_OSTYPE): "
+echo -ne "- OS type ($DEFAULT_OSTYPE): ";
 read OSTYPE
 
 # make sure it is entered
-if [ -z "$OSTYPE" ]; then 
-   OSTYPE=$DEFAULT_OSTYPE
+if [ -z "$OSTYPE" ]; then
+	OSTYPE=$DEFAULT_OSTYPE;
 fi
 
 # ask for hardware setup
-echo "--- Hardware"
+echo "--- Hardware";
 
 # RAM
 DEFAULT_MEMORY=256;
-echo -ne "- RAM in MB ($DEFAULT_MEMORY): "
+echo -ne "- RAM in MB ($DEFAULT_MEMORY): ";
 read MEMORY
-if [ -z "$MEMORY" ]; then 
-   MEMORY=$DEFAULT_MEMORY
+if [ -z "$MEMORY" ]; then
+	MEMORY=$DEFAULT_MEMORY;
 fi
 
 # VRAM
 DEFAULT_VRAM=128;
-echo -ne "- VRAM in MB ($DEFAULT_VRAM): "
+echo -ne "- VRAM in MB ($DEFAULT_VRAM): ";
 read VRAM
-if [ -z "$VRAM" ]; then 
-   VRAM=$DEFAULT_VRAM
+if [ -z "$VRAM" ]; then
+	VRAM=$DEFAULT_VRAM;
 fi
 
 # RAM
 DEFAULT_CPUCAP=50;
-echo -ne "- Max CPU% usage ($DEFAULT_CPUCAP): "
+echo -ne "- Max CPU% usage ($DEFAULT_CPUCAP): ";
 read CPUCAP
-if [ -z "$CPUCAP" ]; then 
-   CPUCAP=$DEFAULT_CPUCAP
+if [ -z "$CPUCAP" ]; then
+	CPUCAP=$DEFAULT_CPUCAP;
 fi
 
 # Disk
-echo -ne "- Disk size in MB (leave empty to not create one): "
+echo -ne "- Disk size in MB (leave empty to not create one): ";
 read DISKSIZE
 
 # VRDEPORT
 DEFAULT_VRDEPORT=3390;
 echo -ne "- VRDE port in MB ($DEFAULT_VRDEPORT): "
 read VRDEPORT
-if [ -z "$VRDEPORT" ]; then 
-   VRDEPORT=$DEFAULT_VRDEPORT
+if [ -z "$VRDEPORT" ]; then
+	VRDEPORT=$DEFAULT_VRDEPORT
 fi
 
 echo "--- Ready to create new VM"
-echo "- Name:      $NAME";
-echo "- RAM:       $MEMORY MB";
-echo "- VRAM:      $VRAM MB";
-echo "- CPU-cap:   $CPUCAP%";   
-echo "- OS type:   $OSTYPE";
+echo "- Name:		$NAME";
+echo "- RAM:		$MEMORY MB";
+echo "- VRAM:		$VRAM MB";
+echo "- CPU-cap:	$CPUCAP%";
+echo "- OS type:	$OSTYPE";
 echo "- VRDE port: $VRDEPORT";
 if [ -n "$DISKSIZE" ]; then
-echo "- Disk:      $DISKSIZE MB (will be named $NAME.vdi)";
+echo "- Disk:		$DISKSIZE MB (will be named $NAME.vdi)";
 fi
 read -p "- Press enter to create " -n 1
 
 # try to make machine
-echo "-- Trying to create VM: $NAME..."; 
+echo "-- Trying to create VM: $NAME...";
 VBoxManage createvm --name "$NAME" --ostype $OSTYPE --register
 if [ ! $? -eq 0 ] ; then
-    echo 'Failed';
-    exit 1
+	echo 'Failed';
+	exit 1
 fi
 
 # try to setup machine hardware specs, accelerate 3d = off since 4.2
 echo "-- Trying to set hardware specifications...";
 VBoxManage modifyvm "$NAME" --memory $MEMORY --acpi on --boot1 dvd --nic1 bridged --bridgeadapter1 eth0 --nictype1 "82540EM" --vrde on --vrdeauthtype null --vrdemulticon on --vram $VRAM --accelerate3d off --cpuexecutioncap $CPUCAP --vrdeport $VRDEPORT --pae on --chipset ich9 --ioapic on --firmware bios
 if [ ! $? -eq 0 ] ; then
-    echo 'Failed';
-    exit 1
+	echo 'Failed';
+	exit 1
 fi
 
 # try to add storage controller
 echo "-- Trying to add storage controller...";
 VBoxManage storagectl "$NAME" --name "SATA Controller" --add sata --controller IntelAHCI
 if [ ! $? -eq 0 ] ; then
-   echo 'Failed';
-   exit 1
+	echo 'Failed';
+	exit 1
 fi
 
 # DVD drive
 echo "-- Trying to add DVD drive...";
 VBoxManage storageattach "$NAME" --storagectl "SATA Controller" --port 1 --device 0 --type dvddrive --medium emptydrive
 if [ ! $? -eq 0 ] ; then
-   echo 'Failed';
-   exit 1
+	echo 'Failed';
+	exit 1
 fi
 
 # if disk is requested
 if [ -n "$DISKSIZE" ]; then
-    # try to create disk
-    echo "-- Trying to create disk...";
-    VBoxManage createhd --filename "/virtualbox/disks/$NAME/$NAME.vdi" --size $DISKSIZE
-    if [ ! $? -eq 0 ] ; then
-        echo "Failed";
-        exit 1
-    fi
+	# try to create disk
+	echo "-- Trying to create disk...";
+	VBoxManage createhd --filename "/virtualbox/disks/$NAME/$NAME.vdi" --size $DISKSIZE
+	if [ ! $? -eq 0 ] ; then
+		 echo "Failed";
+		 exit 1
+	fi
 
-    # try to attach disk
-    echo "-- Trying to attach disk...";
-    VBoxManage storageattach "$NAME" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "/virtualbox/disks/$NAME/$NAME.vdi"
-    if [ ! $? -eq 0 ] ; then
-        echo "Failed";
-        exit 1
-    fi
+	# try to attach disk
+	echo "-- Trying to attach disk...";
+	VBoxManage storageattach "$NAME" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "/virtualbox/disks/$NAME/$NAME.vdi"
+	if [ ! $? -eq 0 ] ; then
+		 echo "Failed";
+		 exit 1
+	fi
 fi
 
 # AUDIO
 echo "-- Trying to add audio ALSA / AC97";
 VBoxManage modifyvm "$NAME" --audio alsa --audiocontroller ac97
 if [ ! $? -eq 0 ] ; then
-   echo "Failed";
-   exit 1
+	echo "Failed";
+	exit 1
 fi
 
 # USB controller
 echo "-- Trying to enable USB controller";
 VBoxManage modifyvm "$NAME" --usb on
 if [ ! $? -eq 0 ] ; then
-   echo "Failed";
-   exit 1
+	echo "Failed";
+	exit 1
 fi
 
 # USB 2.0 controller
 echo "-- Trying to enable USB 2.0 controller";
 VBoxManage modifyvm "$NAME" --usbehci on
 if [ ! $? -eq 0 ] ; then
-   echo "Failed";
-   exit 1
+	echo "Failed";
+	exit 1
 fi
 
 # USB 3.0 controller
 echo "-- Trying to enable USB 3.0 controller";
 VBoxManage modifyvm "$NAME" --usbxhci on
 if [ ! $? -eq 0 ] ; then
-   echo "Failed";
-   exit 1
+	echo "Failed";
+	exit 1
 fi
-
-
-
 
 echo "--- Creation of $NAME is complete.";
diff --git a/vmoff b/vmoff
--- a/vmoff
+++ b/vmoff
@@ -1,12 +1,18 @@
 #!/bin/bash
-# to stop virtual machines
+
+# vmoff
+# virtualbox, turn a machine off
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 12:09:29
+# 2018-06-29 17:00:00 - cleanup
 
 # if machine is specified, stop that
 if [ -n "$1" ]; then
-    VBoxManage controlvm "$1" acpipowerbutton
+	VBoxManage controlvm "$1" acpipowerbutton
 # otherwise stop them all
 else
-    echo "Machine name must be specified.";
-    exit 1;
+	echo "Machine name must be specified.";
+	exit 1;
 fi
-
diff --git a/vmremusb b/vmremusb
--- a/vmremusb
+++ b/vmremusb
@@ -1,8 +1,16 @@
 #!/bin/bash
 
+# vmremusb
+# virtualbox, remove usb device from machine
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 12:09:05
+# 2018-06-29 17:03:00 - cleanup
+
 if [ -z "$1" ] || [ -z "$2" ]; then
-   echo "VM name and USB UUID must be given.";
-   exit 1
+	echo "VM name and USB UUID must be given.";
+	exit 1
 fi
 
 VBoxManage controlvm "$1" usbdetach "$2"
diff --git a/vmrestart b/vmrestart
--- a/vmrestart
+++ b/vmrestart
@@ -1,11 +1,19 @@
 #!/bin/bash
 
+# vmrestart
+# virtualbox, restart a machine
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 11:23:01
+# 2018-06-29 17:06:00 - cleanup
+
 # if machine is specified, stop that
 if [ -n "$1" ]; then
-    vmstop "$1"
-    vmstart "$1"
-    # otherwise stop them all
+	vmstop "$1"
+	vmstart "$1"
+	# otherwise stop them all
 else
-   echo 'VM name must be specified';
-   exit 1;
+	echo 'VM name must be specified';
+	exit 1;
 fi
diff --git a/vmstart b/vmstart
--- a/vmstart
+++ b/vmstart
@@ -1,11 +1,18 @@
 #!/bin/bash
 
+# vmstart
+# virtualbox, start a machine
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 12:08:34
+# 2018-06-29 17:07:00 - cleanup
+
 # if machine is specified, start that
 if [ -n "$1" ]; then
-    nice -n 10 VBoxHeadless --startvm "$1" &
+	nice -n 10 VBoxHeadless --startvm "$1" &
 # otherwise end here
 else
-   echo 'Machine name must be specified';
-   exit 1;
+	echo 'Machine name must be specified';
+	exit 1;
 fi
-
diff --git a/vmstop b/vmstop
--- a/vmstop
+++ b/vmstop
@@ -1,12 +1,18 @@
 #!/bin/bash
-# to stop virtual machines
+
+# vmstop
+# virtualbox, stop a machine
+# by robert klebe, dotpointer
+
+# changelog
+# 2014-10-01 12:09:18
+# 2018-06-29 17:09:00 - cleanup
 
 # if machine is specified, stop that
 if [ -n "$1" ]; then
-    VBoxManage controlvm "$1" poweroff
+	 VBoxManage controlvm "$1" poweroff
 # otherwise stop them all
 else
-   echo 'VM name must be specified';
-   exit 1;
+	echo 'VM name must be specified';
+	exit 1;
 fi
-
